language: node_js
os:
  - windows
  - linux
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: hebbpPcAx+DOhSkIszP3hiq8niebfsGbQG1DbalSLjxLQrLG+o2b5wYdbhJdu0VNqZmzyA7VtNbybu2aHQRul2PlFBc00J4jhlQ8SboT80jhct2FZxOZKLX6D2Tsv7j6WMbi14GyNNPgh3IBACSTpQYITmDBSboejuPqlCMybZV7iKWAcvJdYs6KxkD3AOiIJX0jUO5QZx4nI0MqA1tsCRhoZa0rLY4UtkSnfAPBPgivtmULtrxfPUEC30sp9PPT++l491ZtwtsjXJK4IZJQrlKlwzizIQVKKfAJJgq65i46zsUjv4vC4lHXxYd6QFdhAMra3D+lL7NFWBI7VxCuzx7EyR1/Q4oIetrdFcEDm8cM6AOjNRjraDI8Oi0FjTx7nbnVjHeaTpyqLVmgA47qROe6Bo5zXQZPKqSlsTW8GCbMiC2TbZFKeyhRbYyuPlDWBlzKYo8TxMPAhk5BmL+L/P7SiU/w1/Xc1kBlNqouhY4hmHumtEJZ96OXS9CZI0BCzX6t2D59Y5rrHE9L9/3i6qAvxD4iZepQzwlS+ph4oC0PrtOaJibSWcGbZ7eLL6RQ4IGN/gZ+5qfiPaYVU0IYoRi6dsU07BmuvrIWmm4BNw6vdIFqnrn5l9qU03Qj00gX8W/FYy9VoXKlh3uW6aqY8I411HpkgBP+ol9wKGgNrXI=
  file:
    - 'remark-contributors.js'
    - 'remark-contributors.min.js'
  on:
    tags: true
